### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'carpetskyadditions'!

### ISSUE THREAD

**Issue by jnthnjns** [jsorrell/CarpetSkyAdditions#115]
I can't even launch with Skyadditions and I'm trying to track down the cause. I'm getting the following:

```
Could not execute entrypoint stage 'main' due to errors, provided by 'carpetskyadditions'!
```

If I disable skyadditions then it works fine. Still getting the error when I disable all mods except what skyadditions (screenshot at bottom). Also, see stack trace below and addtional logging below.

Minecraft version: 1.19.4
Launching from MultiMC: 0.7.0-3739 on win32

**Stack**
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'carpetskyadditions'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 621.1 
```

----

**Larger log:**
```
[20:40:37] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[20:40:37] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[20:40:38] [main/INFO]: Loading 57 mods:
	- carpet 1.4.101+v230319
	- carpetskyadditions 1.19.4-4.3.1
	- cloth-config 10.0.96
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.79.0+1.19.4
	   |-- fabric-api-base 0.4.24+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.25+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.7+348a9c64f4
	   |-- fabric-block-api-v1 1.0.6+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.34+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.15+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.27+f71b366ff4
	   |-- fabric-command-api-v2 2.2.6+e719b857f4
	   |-- fabric-commands-v0 0.2.44+df3654b3f4
	   |-- fabric-containers-v0 0.1.54+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.9+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.1+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.15+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.4.0+6cebf059f4
	   |-- fabric-dimensions-v1 2.1.45+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.13+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.43+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.52+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.33+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.17+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.5+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.33+c477957ef4
	   |-- fabric-keybindings-v0 0.2.31+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.15+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.27+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.31+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.1+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.39+49abcf7ef4
	   |-- fabric-models-v0 0.3.30+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.3.1+a6f3ccfaf4
	   |-- fabric-networking-v0 0.3.41+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.3+63b515f4f4
	   |-- fabric-particles-v1 1.0.23+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.8+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.2.0+670e8ac6f4
	   |-- fabric-renderer-api-v1 2.2.5+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.1+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.38+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.28+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.21+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.41+df3654b3f4
	   |-- fabric-rendering-v1 2.1.1+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.1+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.2+1e1fb126f4
	   |-- fabric-screen-api-v1 1.0.45+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.20+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.9+75e98211f4
	   |-- fabric-transfer-api-v1 3.1.1+da9bb835f4
	   \-- fabric-transitive-access-wideners-v1 3.0.3+63b515f4f4
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.19.4
[20:40:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Games/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:40:39] [main/INFO]: Compatibility level set to JAVA_17
[20:40:44] [Datafixer Bootstrap/INFO]: 182 Datafixer optimizations took 97 milliseconds
[20:40:46] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:40:46] [Render thread/INFO]: Setting user: DingusOptimus
[20:40:46] [Render thread/WARN]: Method overwrite conflict for getConnection in fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric-networking-api-v1, previously written by carpet.mixins.ServerGamePacketListenerImpl_coreMixin. Skipping method.
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-04-28 20:40:46
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'carpetskyadditions'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 621.1 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.6.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.6.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.6.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.6.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.1485 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.6.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.6.0:Microsoft
		win32u.dll:Win32u:10.0.22621.1555 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.6.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
---

System information
```
-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 8130078968 bytes (7753 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900KF
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x220a
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 34664.00
	Virtual memory used (MB): 19571.69
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 38.18
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

I've stripped out all of my mods and still finding it difficult to launch, getting the same error.

![image](https://user-images.githubusercontent.com/339960/235273952-5105ef4a-8a25-4b14-88d2-e18019908a9d.png)

**Comment by jsorrell** [comment]
All your versions look correct. This looks like it might be a settings issue due to `java.lang.IllegalStateException: Key is not followed by an equals sign on line 1` which I think is thrown by a toml parser. Try deleting `config/carpetskyadditions.toml`.

**Comment by jnthnjns** [comment]
That was it, thank you!
