### ISSUE TITLE
Mod 'Carpet Sky Additions' (carpetskyadditions) 1.20.1-4.3.2 requires any version of cloth-config2, which is missing!

### ISSUE THREAD

**Issue by Chanpoe** [jsorrell/CarpetSkyAdditions#127]
My Minecraft version is 1.20.1.
Here are the error details.

```
E:\Games\forge-kongdao-1.20.1-server>java -Xmx2G -jar fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[14:12:55] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[14:12:56] [main/WARN]: Mod resolution failed
[14:12:56] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE carpetskyadditions 1.20.1-4.3.2 {depends cloth-config2 @ [*]}, ROOT_FORCELOAD_SINGLE carpetskyadditions 1.20.1-4.3.2]
[14:12:56] [main/INFO]: Reason: [HARD_DEP carpetskyadditions 1.20.1-4.3.2 {depends cloth-config2 @ [*]}]
[14:12:56] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-models-v0, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-rendering-v0, fabric-sound-api-v1, fabric-key-binding-api-v1, fabric-rendering-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[14:12:56] [main/INFO]: Fix: add [add:cloth-config2 1 ([(-∞,∞)])], remove [], replace []
[14:12:56] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install cloth-config2, any version.
Unmet dependency listing:
         - Mod 'Carpet Sky Additions' (carpetskyadditions) 1.20.1-4.3.2 requires any version of cloth-config2, which is missing!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
```

What should I do to fix this error?

**Comment by Chanpoe** [comment]
> i had the same message, downloaded this file and it works for me https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/4554906
Thank you for providing the solution. The problem has been resolved. Thank you.
